-- ========================================
-- 已废弃：文档分块数据已迁移至 PostgreSQL rag.document_chunk
-- 本文件仅作历史参考，所有 SQL 已注释，不可执行
-- ========================================

-- DROP TABLE IF EXISTS kb_document_chunk;
-- CREATE TABLE kb_document_chunk (
--     id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
--     doc_id          BIGINT       NOT NULL COMMENT '所属文档 ID（关联 kb_document.id）',
--     kb_id           BIGINT       NOT NULL COMMENT '所属知识库 ID（冗余，方便按 kb 清理）',
--     chunk_index     INT          NOT NULL COMMENT '分块序号（从 0 开始）',
--     title           VARCHAR(256) NULL COMMENT '文档标题',
--     section_path    VARCHAR(512) NULL COMMENT '章节路径（如 "集团开票信息汇总 > 阿里巴巴"）',
--     content         TEXT         NOT NULL COMMENT '分块文本内容',
--     token_count     INT          NOT NULL DEFAULT 0 COMMENT 'Token 数量',
--     char_length     INT          NOT NULL DEFAULT 0 COMMENT '字符长度',
--     embedding_text  TEXT         NULL COMMENT '用于生成向量的文本（= title + sectionPath + content）',
--     version         INT          NOT NULL DEFAULT 1 COMMENT '文档版本号（与 kb_document.version 同步）',
--     created_time    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--     PRIMARY KEY (id),
--     INDEX idx_doc_id (doc_id),
--     INDEX idx_doc_version (doc_id, version),
--     INDEX idx_kb_id (kb_id)
-- ) ENGINE = InnoDB
--   DEFAULT CHARSET = utf8mb4
--   COLLATE = utf8mb4_unicode_ci
--   COMMENT = '文档分块表';
